package report

// Branding customizes exported assessment reports.
type Branding struct {
	Organization string `json:"organization"`
	Classification string `json:"classification"`
	LogoURL      string `json:"logo_url,omitempty"`
	Footer       string `json:"footer,omitempty"`
}

// DefaultBranding returns lab-safe defaults.
func DefaultBranding() Branding {
	return Branding{
		Organization:   "Veil Engage",
		Classification: "CONFIDENTIAL",
		Footer:         "Generated by Veil Engage — authorized testing only",
	}
}
