#!/usr/bin/env python3
"""P9f gate: every catalog tool must dispatch without unknown/disabled and return success."""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "engage/serve/catalog/tools.yaml"
GAPS_DOC = ROOT / "docs/engage/engage-executable-gaps.md"
MATRIX_CMD = ["go", "run", "./cmd/executable-matrix/", "--root", str(ROOT)]
EXPECTED_TOOLS = 158


def parse_catalog_names(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    names = re.findall(r"^  - name: (\S+)", text, re.M)
    return names


def run_matrix() -> tuple[list[dict], int, int]:
    proc = subprocess.run(
        MATRIX_CMD,
        cwd=ROOT / "engage/serve",
        env={**dict(**__import__("os").environ), "GOWORK": str(ROOT / "engage" / "go.work")},
        capture_output=True,
        text=True,
    )
    total = 0
    passed = 0
    for line in proc.stderr.splitlines():
        if line.startswith("MATRIX_TOTAL="):
            total = int(line.split("=", 1)[1])
        if line.startswith("MATRIX_PASS="):
            passed = int(line.split("=", 1)[1])
    results: list[dict] = []
    for line in proc.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        results.append(json.loads(line))
    if proc.returncode not in (0, 1) and not results:
        sys.stderr.write(proc.stderr)
        sys.stderr.write(proc.stdout)
        raise SystemExit(proc.returncode or 2)
    return results, passed, total or len(results)


def write_gaps_doc(names: list[str], failures: list[dict]) -> None:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Engage executable matrix gaps",
        "",
        f"Auto-generated by `scripts/engage/check-executable-matrix.py` ({ts}).",
        "",
        f"Catalog tools: **{len(names)}**. Failures: **{len(failures)}**.",
        "",
        "| Tool | Route | Error |",
        "|------|-------|-------|",
    ]
    for row in sorted(failures, key=lambda r: r["name"]):
        err = (row.get("error") or "").replace("|", "\\|").replace("\n", " ")
        lines.append(f"| `{row['name']}` | {row.get('kind', '')} | {err} |")
    lines.extend(
        [
            "",
            "Regenerate: `make test-engage-executable-matrix`.",
            "",
        ]
    )
    GAPS_DOC.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", type=Path, default=CATALOG)
    parser.add_argument("--expected", type=int, default=EXPECTED_TOOLS)
    args = parser.parse_args()

    names = parse_catalog_names(args.catalog)
    if len(names) != args.expected:
        print(
            f"FAIL: catalog has {len(names)} tools, expected {args.expected}",
            file=sys.stderr,
        )
        return 1

    results, passed, total = run_matrix()
    failures = [r for r in results if not r.get("pass")]
    print(f"engage executable matrix: {passed}/{total} PASS")

    if failures:
        write_gaps_doc(names, failures)
        print(f"gaps written: {GAPS_DOC.relative_to(ROOT)}", file=sys.stderr)
        return 1

    if GAPS_DOC.exists():
        GAPS_DOC.unlink()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
