#!/usr/bin/env bash
# Enable catalog tools when their binary is on PATH; writes tools.enabled.yaml (does not mutate tools.yaml).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CATALOG="${ENGAGE_CATALOG_PATH:-${ROOT}/engage/serve/catalog/tools.yaml}"
ENABLED="${ENGAGE_ENABLED_CATALOG:-${ROOT}/engage/serve/catalog/tools.enabled.yaml}"
CATEGORIES="${*:-network web osint cloud}"

if [[ ! -f "${CATALOG}" ]]; then
  echo "catalog not found: ${CATALOG}" >&2
  exit 1
fi

python3 - "${CATALOG}" "${ENABLED}" ${CATEGORIES} <<'PY'
import re, shutil, sys
from pathlib import Path

catalog = Path(sys.argv[1])
enabled_out = Path(sys.argv[2])
categories = set(sys.argv[3:])
text = catalog.read_text(encoding="utf-8")
blocks = re.split(r"(?=  - name: )", text)
header, *entries = blocks[0], blocks[1:]
out_blocks = []

for block in entries:
    if not block.strip():
        continue
    name_m = re.search(r"^\s*- name: (\S+)", block, re.M)
    cat_m = re.search(r"^\s*category: (\S+)", block, re.M)
    bin_m = re.search(r"^\s*binary: (\S+)", block, re.M)
    if not name_m or not cat_m or not bin_m:
        continue
    cat, binary = cat_m.group(1), bin_m.group(1)
    if cat in categories and shutil.which(binary):
        b = re.sub(r"^\s*enabled: false\s*$", "    enabled: true", block, count=1, flags=re.M)
        if "enabled:" not in b:
            b = b.rstrip() + "\n    enabled: true\n"
        out_blocks.append(b.rstrip("\n"))

lines = ["# Auto-generated by enable-catalog-by-category.sh", "tools:"]
lines.extend(out_blocks)
enabled_out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {len(out_blocks)} enabled overrides to {enabled_out}")
PY
